### ISSUE TITLE
Adding workflow for LED repo

### ISSUE THREAD

**Issue by andreasdahl1987** [andreasdahl1987/DahlDesignLED#1]
@mcowger @photon1503

Is is much work adding the same workflow for .dll building in this repo?

https://github.com/andreasdahl1987/DahlDesignProperties/pull/10

**Comment by photon1503** [comment]
@andreasdahl1987 should be easy, it's more or less the same build process like for DahlDesignProperties.

But I am confused... there are two Solution and csproj Files in the repo. Which one to take?

Created a new pipeline for "Dahl Design LED controller.sln" in my fork of the project and buildt the DLL. Please find it at [DahlDesignLED.dll](https://github.com/photon1503/DahlDesignLED/releases/download/1/DahlDesignLED.dll) and let me know if it works for you. 

If it's fine than I can create a pull request.

**Comment by andreasdahl1987** [comment]
Oh, that's strange. I'll find out what happened and give some feedback

**Comment by andreasdahl1987** [comment]
@photon1503 I've removed the two unused files. The "Dahl Design LED controller.sln" was  actually the wrong one. Should all be in order now, build that I've made with this project is working, I didnt test yours.
